### ISSUE TITLE
Setting for plain world or height

### ISSUE THREAD

**Issue by 3ttu** [Tamaized/Void-Fog#16]
I suggest making a setting at what height the fog starts or a Boolean option to turn off fog in a flat world

**Comment by AriaElidove** [comment]
There is already a client config where you can change the fog height. 

![image](https://github.com/Tamaized/Void-Fog/assets/144502047/ac2d838a-1b18-4bb5-8720-c8befe1119b7)

**Comment by Tamaized** [comment]
Yeah you can set the value to 1 if you wish.
