### ISSUE TITLE
server crash (low prio)

### ISSUE THREAD

**Issue by Lucky-56** [Tamaized/Void-Fog#17]
please tag your mod as client sided for easier management of removing client sided mods from a modpack for server use

**Comment by Tamaized** [comment]
The mod can actually exist on a server and wont crash, there's safeguards in place. But Yeah I should do that regardless.

**Comment by Lucky-56** [comment]
but it did crash mine earlier... that's why I reported, but now it works huh demo effect I guess

**Comment by Lucky-56** [comment]
maybe because I had Yung's Menu Tweaks enabled aswell and the crash just threw your mod at me I guess

**Comment by Lucky-56** [comment]
double nevermind CurseForge was playing tricks on me,
[this is the log of only your mod on server side](https://mclo.gs/8N2pwQa)

**Comment by Tamaized** [comment]
I've marked the 1.20.4 and 1.20.1 versions on curseforge.

Anyway.. looks like I need to fix the crash.. I know why it's happening too. Oops!

**Comment by Tamaized** [comment]
Looks like this is fixed in the currently published 1.21 build
