### ISSUE TITLE
Distant Horizons support

### ISSUE THREAD

**Issue by coaber** [Tamaized/Void-Fog#19]
void fog does not render at all with DH installed, only the particles. is DH support planned for the future maybe?

**Comment by Tamaized** [comment]
If they are breaking the forge fog events... that's on them.

**Comment by coaber** [comment]
i did some further testing, turned off their fog rendering and the void fog sorta comes back but its cut off straight where the LOD rendering starts. will report this on DH's side.

**Comment by Tamaized** [comment]
They bypass the forge events entirely and disable fog :/
https://gitlab.com/distant-horizons-team/distant-horizons/-/blob/main/forge/src/main/java/com/seibel/distanthorizons/forge/mixins/client/MixinFogRenderer.java?ref_type=heads

People really shouldn't be allowed to use mixins if they don't understand what they're doing. There's a forge event for a reason.....

For example, if they actually used the event then i could solve this by setting my listener priority to run after their's but no... they force themselves to run last always.

**Comment by Tamaized** [comment]
It does however appear they have some "disableVanillaFog" config that you can set to false which might fix it?
