### ISSUE TITLE
Crashes Upon loading World [1.12] 

### ISSUE THREAD

**Issue by NoplixDE** [Tamaized/Void-Fog#3]
Hi me again xD

The title says it.

Error: https://gist.github.com/NoplixDE/fe05c75a36c9aabf7a79660605b6d254

**Comment by Tamaized** [comment]
Ah yep, I forgot to update this mod after I updated VoidCraft, so it'll work with the older versions of VoidCraft but not the newer ones. I'll get around to it~

**Comment by Tamaized** [comment]
Version 1.1.2 should fix this
