### ISSUE TITLE
[1.10] Incorrect mcmod.info

### ISSUE THREAD

**Issue by asanetargoss** [Tamaized/Void-Fog#4]
"mcversion" should be 1.10.2, otherwise Forge complains.

Minecraft and the mod run fine when mcmod.info is updated with the appropriate mcversion value.

**Comment by Tamaized** [comment]
eh, that's what I get for allowing the jar to work on multiple versions

**Comment by Tamaized** [comment]
Actually wait, where does it complain exactly?

**Comment by asanetargoss** [comment]
Strange; I can't seem to reproduce it today with the exact same mcmod.info replacement in the exact same environment. All I did was replace the jar with a version of the jar with mcmod.info replaced.

The behavior I was trying to reproduce is similar to what happens when you are missing a mod that another mod depends on, (Forge initialization ends early, Minecraft music plays, dirt background, single Forge error message), except the message is about a mod wanting a required Minecraft version.

Forge [does seem to have code](https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/src/main/java/net/minecraftforge/fml/common/FMLModContainer.java#L257) for falling back on the Minecraft version mcmod.info file when the \@Mod annotation is not present, although why exactly Forge would fail to see your \@Mod annotation is a mystery to me.

**Comment by Tamaized** [comment]
I'm thinking you used the 1.12 version in 1.11 and below, that's the only thing that would cause this

**Comment by asanetargoss** [comment]
The \@Mod annotation of the mod class from the same jar whose mcmod.info file I altered is:

`@Mod(modid="voidfog", name="VoidFog", version="1.0.1", clientSideOnly=true, guiFactory="Tamaized.VoidFog.config.GUIConfigFactory", acceptedMinecraftVersions="[1.8,1.11.2]")`

¯\_(ツ)_/¯

**Comment by Tamaized** [comment]
odd, not sure how it failed then
